# This is a basic workflow to help you get started with Actions

name: doc_upload

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches: [ "main", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Select sync files
        run: mkdir ./__sync_rdme && cp ./Documents/Reference.md ./__sync_rdme/Reference.md
      - name: rdme 🦉 Sync to ReadMe
        # You may pin to the exact commit or the version.
        # uses: readmeio/rdme@f90d26865ddd19a76295273bcd9c98b130529c6a
        uses: readmeio/rdme@8.1.1
        with:
          # Command to pass into rdme
          rdme: docs ./__sync_rdme --key=${{ secrets.README_API_KEY }} --version=2.0
